PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS authors (id TEXT PRIMARY KEY, name TEXT NOT NULL, bio TEXT, avatar_base64_chunks TEXT DEFAULT '[]', verified INTEGER DEFAULT 1, role TEXT DEFAULT 'editor', created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS articles (id TEXT PRIMARY KEY, slug TEXT UNIQUE NOT NULL, title TEXT NOT NULL, dek TEXT NOT NULL, body TEXT NOT NULL, category TEXT NOT NULL, tags TEXT NOT NULL DEFAULT '[]', author_id TEXT NOT NULL, status TEXT CHECK(status IN ('draft','published','archived')) DEFAULT 'draft', hero_base64_chunks TEXT DEFAULT '[]', seo_json TEXT NOT NULL, views INTEGER DEFAULT 0, revenue_slots TEXT DEFAULT '["top","inline","rail"]', fact_check_notes TEXT DEFAULT '', ai_disclosure TEXT DEFAULT 'AI assisted draft; human reviewed before publishing.', published_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(author_id) REFERENCES authors(id));
CREATE TABLE IF NOT EXISTS media_assets (id TEXT PRIMARY KEY, hash TEXT UNIQUE NOT NULL, prefix TEXT NOT NULL, mime TEXT, bytes INTEGER DEFAULT 0, chunk_count INTEGER NOT NULL, storage_manifest TEXT NOT NULL, alt TEXT DEFAULT '', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS traffic_events (id TEXT PRIMARY KEY, article_id TEXT, path TEXT NOT NULL, ip_hash TEXT NOT NULL, ua_hash TEXT NOT NULL, country TEXT, referrer TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, article_id TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, min_views INTEGER DEFAULT 1000, status TEXT CHECK(status IN ('queued','sent','cancelled')) DEFAULT 'queued', sent_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS push_subscriptions (id TEXT PRIMARY KEY, endpoint TEXT UNIQUE NOT NULL, keys_json TEXT NOT NULL, min_views INTEGER DEFAULT 1000, enabled INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS redirects (source TEXT PRIMARY KEY, target TEXT NOT NULL, status INTEGER DEFAULT 301, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS seo_audits (id TEXT PRIMARY KEY, article_id TEXT, score INTEGER NOT NULL, checks_json TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS article_revisions (id TEXT PRIMARY KEY, article_id TEXT NOT NULL, editor TEXT NOT NULL, title TEXT NOT NULL, dek TEXT NOT NULL, body TEXT NOT NULL, seo_json TEXT NOT NULL, revision_note TEXT DEFAULT '', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(article_id) REFERENCES articles(id));
CREATE TABLE IF NOT EXISTS topic_taxonomy (id TEXT PRIMARY KEY, type TEXT CHECK(type IN ('category','tag')) NOT NULL, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT DEFAULT '', created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS correction_requests (id TEXT PRIMARY KEY, article_id TEXT, article_slug TEXT, email TEXT NOT NULL, message TEXT NOT NULL, status TEXT CHECK(status IN ('open','reviewing','resolved','rejected')) DEFAULT 'open', created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS newsletter_subscribers (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, status TEXT CHECK(status IN ('active','unsubscribed')) DEFAULT 'active', source TEXT DEFAULT 'site', created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_audit_log (id TEXT PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT, metadata_json TEXT DEFAULT '{}', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_articles_status_pub ON articles(status, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_category ON articles(category, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_slug ON articles(slug);
CREATE INDEX IF NOT EXISTS idx_traffic_article ON traffic_events(article_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_push_enabled ON push_subscriptions(enabled, min_views);
CREATE INDEX IF NOT EXISTS idx_corrections_status ON correction_requests(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_newsletter_status ON newsletter_subscribers(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_revisions_article ON article_revisions(article_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_taxonomy_type ON topic_taxonomy(type, slug);
